{{/* Template file for UI definitions*/}}

/* This file is generated by uigen; DO NOT EDIT */

{{range .Boilerplate}}
{{.Text}}
{{end}}

#include <stddef.h>
#include <stdint.h>

struct menu;

struct editable_item {
	const char *label;	/* NULL if integer range */
	int value;
};

struct editable {
	const char *display;
	int (*get)(void);
	int (*set)(void);
	int range_lo, range_hi;	/* If no integer range, then hi<lo */
	size_t n;
	const struct editable_item *items;
};

struct ask_item {
	const char *label;
	void (*action)(void);	/* NULL to return to previous menu */
};

struct ask {
	const char *display;
	size_t n;
	const struct ask_item *items;
};

struct submenu_range {
	const char *label;
	int (*set)(void);
	int range_lo, range_hi;	/* If no integer range, then hi<lo */
	struct menu *definition;
};

struct menu_item {
	const char *label;
	enum { M_EDITABLE, M_ASK, M_SUBMENU, M_SUBMENU_RANGE } mi_type;
	union {
		struct editable *editable;
		struct ask *ask;
		struct menu *submenu;
		struct submenu_range *submenu_range;
	} item;
};

struct menu {
	size_t n;
	struct menu_item *items;
};

/* Forward declaration of menus */
{{range .Menus}}struct menu {{.Name}};
{{end}}
{{range .Menus}}/* {{if eq .Name "root"}}Root menu{{else}}Menu "{{.Name}}"{{end}} */

{{range .Editables}}
{{if .Items}}
struct editable_item {{.Name}}_items[] = {
{{range .Items}}	{ "{{.Label}}", {{.Definition}} },
{{end}}};{{end}}

struct editable {{.Name}} = {
	"{{.Label}}",
	{{.Get}},
	{{.Set}},
	{{if .HasRange}}{{.RangeLow}}, {{.RangeHi}},
	{{else}}0, -1 /* no integer range */
	{{end}}{{len .Items}},
	{{if .Items}}{{.Name}}_items{{else}}NULL{{end}},
};
{{end}}
{{range .Asks}}

{{if .Items}}
{{range .Items}}{{if .Action}}void {{.Action}}(void);
{{end}}{{end}}
struct ask_item {{.Name}}_items[] = {
{{range .Items}}	{ "{{.Label}}", {{if .Action}}{{.Action}}{{else}}NULL{{end}} },
{{end}}};
{{end}}
struct ask {{.Name}} = {
	"{{.Label}}",
	{{len .Items}},
	{{if .Items}}{{.Name}}_items{{else}}NULL{{end}},
};
{{end}}

struct menu_item {{.Name}}_items[] = {
{{range .Items}}	{
		.label = "{{.Label}}",
{{if eq .Type "editable"}}		.mi_type = M_EDITABLE,
		.item = { .editable = &{{.Name}} },
{{else if eq .Type "ask"}}		.mi_type = M_ASK,
		.item = { .ask = &{{.Name}} }
{{else if eq .Type "submenu"}}		.mi_type = M_SUBMENU,
		.item = { .submenu = &{{.Name}} }
{{else if eq .Type "submenurange"}}		.mi_type = M_SUBMENU_RANGE,
		.item = { .submenu_range = &{{.Name}} }
{{else}}#error unknown menu item type "{{.Type}}"
{{end}}
	},
{{end}}
};

struct menu {{.Name}} = { {{len .Items}}, {{.Name}}_items};

{{end}}

